apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: git-creds
 
spec:
  encryptedData:
    password: AgCF3rxvaigfiR5sQWK+gJVEDYAaq5d13OiB6oUEb6h/vuoDvFXWi6PZjrnuzBbvGqs2wrQQ3CjYtxUNKPeo42lZ84KPlX15817g2Aa9IAmTU+4vdT1Nxh04o+i0OIyt6XVjNzqKHN/Vx6lBB2kep0uD49fy7eg3ElKVjcrOq30/zn/55ymzlNNp8b4n+bztRckCTwGeT4TxnYetB/zoH7wfEXjYTNSvrrHhmQz90LWDJNgNgbfG1fQxgJIMx0DYHp5V9KDdUr21D296jFfnC3gg7rteCvo5EpqEeMeRbqjB9REAGe2ebfOqachbmxvfMvjvz0iqlDg+uO6P+DhFudf1z6DV6WrDFn2JNH/lNRHCgVT5TuftCQ50pKJXNSSImX4Md+mUV4axAXuCcYFz8i+FYJBwJ9YTFt5OGBhx2IgjYLx+6u/RGRDSzx9NrySdRqdYrlv2lLc6CPZKwar/9OAuMtaEhnFyePCImg6pBIYBmYrjDBlqvXk+nLbBe+UunhR+RCgstr5fxM5ppPvtSGLlf30rHOLLcTmy0U1/lKHnmYZ0KOtgd3lpN5bhG7V1m1H74p2+BOWPSTXAl050134HQpY5IF9I6K/Wn2A+A7Yxkvb3Yy29j1uOYqcVAFdNDC5JH/CknqgYrI3Wg8ZiQ3KZDDwzkW4BSH6z3RhYf6kdnqVKt+bm3Sg8T/lCZd/n4FG03a3wRC70t/Nw4+F/pPQUrCSOBzjjEUu6eu8g4L0BnXa2SaNyNeyaWhviPiQvqhnoP7xjTzhtoAOVy+U2ffLYOOTtx1vpEZRbKgKDrj5BP+CjPQ3SMeMQpRszNPo=
    username: AgB4G/GlVefJ8nftLYhitXu02mGIHaSIPLmJdHfZYedveWg21cb4Ftih0vXpJHzDr4KQUJkJAsmBe/RC6y/JxajpIClDm8q/CPYo031341S0S5UUt5FDelLRauWeEkPTf6KcHHCUUf3gDyAOoMPbeZ7Is9A5QMvtbq/IKg5f7RMJIUxvOhlGyXHws9CWcE9NFNojWlzr1XejtxRekKy9tt+6qVeihZRGVAVT/1DhHJbOFo5uRfF8fQqxS0kcanxgw0+GGm3bz1VLXTV6L63JaghCHdkorePChTmEn5L6UZE1xpr7/wUwAEnF7ck2zhAXHafar8v89sXzMneMv0Xh7XTNdBmJcnRhJAxkINwv9vPR8KeiuWRzABK6b5RAwBVkywzj2sTftApMFf4kvu0Wn+bZL9+usOiBsI/HSmqbWTS/oPqSvbAfO8fkfdJcNT9qA6VbFSjbNVFgVZDVY841d7iLeoFZa/aT68i7Ae8a8qiNcB1Hk5HhXCt0Y5tUXH8PnTyWJwtDWAdnRf4AOnIJhowLli15oQEPFn+u3YgiuhJHcLF2ycbpjdsD+YFTz8uCQOSgOxwdN5TVfZoIelKxUm0/7oFDxkCS7oOsPand+AHDb46xxuSc2MUwZ9twhYVb6AayL1bERQgfyKB7CxERZWIJdLByal3unMGZZ1EOz5VwArsAqDCmmXlUUq+zHnxmhShI4MkFaKAtkQ+f
  template:
    metadata:
      creationTimestamp: null
      name: git-creds
      namespace: argocd
    type: Opaque
---
