apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: backend-secret
spec:
  encryptedData:
    DB_PASSWORD: AgBzhF7HZ0hPSLOPaSMMbxq7tudT8hstMaIuhUvqKxo8WLMWEx9I7fvZcrzqiJ5WvCcRCz7KXcmgA0n4jrDU7fNqmbCBBxzbgADfTInnQ7O/232d1/Tdu6bIix+WXwsAb/L5EH7OUpxNpdRrDvG8yKdInvQyx8EYKcFtVE7GVVUfYVR5WL/Uwn0/ivOlBt4GhA9CqwpMOTiez0ychHjZqF+vJijHjmI/kCL+FCVcDZTZTVkyIk68TKq//cMOAU7srpy2NUfByK74w5Vxx5wXjlIfQLApk1dl/cAXzueOV7iJXaHGI47PF+2ZHwKyWiaidPPyoQHyIg43hq9TVqsj28vbh6V9Iqk2ZgCRqQGk0Np11NqKCMhE1VgG+PcjoJ7ngXbK180jCCQkcgmhHlIC+SvgvpySLYBEpaQvNRxsta3ECeEYsZQw7kPu1N82co5vS+zVJmJg70Gg7greeaeIensVAoPfXJATj7m4+j3gtmxasr3oQ8S8aHtyyDbuKADIxjlFWwtN45UWdXGkGAL0iSn/oa/oTzW0J7w5TD9IFjZVg+norkYsONrODOJ+C5hJddKwIoyCOKFN5dYkKjCqnUIkYd7ybvrNoJhNbvnKBTq+KSM34496/UON63CiBXv8/0VwJiGvRCFNFPAe1ht62/AGaz25YBfEJ6BSDsvE13dE/dVLRAlRJH704fml38fHVy9Dz+d2JKsVTdSUXvDB
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: backend
      name: backend-secret
      namespace: default
    type: Opaque
---
