apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: backend-secret
  namespace: backend
spec:
  encryptedData:
    DB_PASSWORD: AgCrt9GDx44fDJj3b/zC8D0xdyXCHW8+Gr11+JMvR7IFVURNVkDCkdky4xeGuSFgC3s5+uWsYouJ/n+ibdeJ/en9UBqk00kB0WngXmwmV7Ri0fHPDRiCiXID8MGAlK4AsJQ1e3eLMwxIIcIAnxCVb/ohLDCPl5v/wKjV5nrCqMzsnw5u754xhe34GRvSZPXky3y8WvgOMR2/L3yuJc1VID8V8QpAklvJQwBdXq1Qpnfh5qOHEprDDp5yVlHdfqhve6w3qtYsMTvWQ85wbf0WqQrOYkGwjmE3h08Eq0KPNDzAX4SfTPHxKvK59gqFzM0ZfuC9Iz/MClsvdMgOv2IGU9cUT+mIK/x3TrdPaCklk4V8uGobIP7sls0NcYikUryQ9qdBgKY98PuyZXX1RJAO3n94SejegblrPH8Mx1CArHN344Yt8s5ceoGagjRVkHbeOMJK7VxXt+PJjjSidqIoXGnwbenNy2088tHPOTf57FA9FgX6b1DS6VCEso1cyONIK4DQ9mflSvs6NEw4LXIw9lqYwkV+adr/1L9jzzY1m+pcFhPZC8NXnYMV7iwJ0+0/kzBMtDlR3YLTnqbRKC+GLJS8G/KcLZwHPsZS2T3rku3rSTx8j8iPF5gCb3RcPTD7VomDuHt4YTAM6wX3sZLthSQhqZy0CVQkH0TfZHVMbAvEHSPjK0khKpmqlYlZtWNMYPVjIhK8Pw6N89ZXxTjZ
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: backend
      name: backend-secret
      namespace: backend
    type: Opaque
---
