apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: docker-hub-creds

spec:
  encryptedData:
    password: AgBVfISbRcHuU4Td9bRiHkxmt7HyroSUa+0sMtmTI4emwFOe61IlR3wzzIsqilgMIjqkauAVOpPfI9y00IGEu9b/SCODA94h2v74Shruu3p/d4CtrsA0qOE4EHyO2OuDVxFYCn+zfHQrXVrDx+qp5SzRI+ZRCRK4PEVca8FBqDlIpT6rL4642AckCzj4uj8UEGQshs5EYdzhWJgCYKAuqlGwvTzuc4PjtSdgjwtqGbfECww7G251Jf/tKMerB9/GSyN9MgPg8/PjQ/yfRzHXiIhsJZENymkAKr9Lbz3KeJva1QxUME39cr9s1sxlzIwUqrBoRr4X+jxnkSp73gZH1Itg8k599KaGxMRNkYcTJlEJRVui9B9zRU1XmzOZtuwM2sLkvML9QESdqdghXy95PjfPtYqTCECUSanrNutd/Qd56KY0NpjwPVnUJbAA4V6kVKK0y94Sf2yo8mRt32dgBpDyg8FSUyvV6o1HRl2MWeQYley7AABhtTsyhoXVAb1+Kr0oEZ8WYWumBmYZPwNk2yKC6tfG093acZJeiMGJozcJPPA3I+sNKC4VlOwYpnXIYVOJ5YznCS/SwW+c0h/QEnI5/T+HeL1povpeUm47FYsxFc/4sxNXNRwYUTWVnv7qLdRgtSgKKujrzTcTOPD/tGhTjp0sAlrXa+sM84l7CC+OVCbE87wk0PanDU8YpFWmqZXrZPfBF6EyO6iwTX2Ub4YK4zu1ASShs5oPqe29RHUxgaXDGRw=
    username: AgCyYlend/WFdrAHyjpD+ArC53VO7ABvDsi7bcLHJ2rNswKrifmNhGqCg3z/aD1iolp1okr+kA3uCSH9lKgjq0688+2K9blO2qYHmn3IhTm4V/e+dEaia5i7mtUP+UU8y798ybBdM4YgGYnufH9tdHAEiYcmob8yPcWVuwwYPwHH8jv98o2fsXote7A3aM+r1yat/mCzUDvPYtin2jiXPzLPewQgzmCHkshHkCsr2St8Us9SzUtVtYJAXThQHSPrrLtwYwGG1/PfhS88X5NjQQCB/lBDvO3wi27FSCd6FkPiOeKB6sDt3oun1/QD3pbxRiCEM9sMiOpJmADmLcj+5H7LQxF+YMCdyVU7x0LXzrSeGQbFA1H7WXqGV1kdJeJco+1NT2/r9MaIxFVg93TNbJKTxJ9bUTPBh+8GnNUH+5wN5I8CAMtvSX57NG/5dOY/WZHIqW7xETMrJ6pCoKnZEx8eQ/1NsuWGzr3KgwXsbKbLa+V5w1UZNs/KQFXIYXj1nkxVz0zBaEdiJ0WZE/q5tyZIV3mfTLcBk5f+u+V/KzHfFJf+5rkMwS9rCAk63EBk+Ka55cPDHlQNLeZ9yBWTJgxWDRt7qWntcIs/GTjBcGyQzB7GfugwXJYPnfMxu3lV3lxCxJwwoSXLR/ihRelKoWO7jzfp2+5zLl17x3X750Cy2/R7HkAa55zCktoIahVc5UCtJzF2YhS4rg==
  template:
    metadata:
      creationTimestamp: null
      name: docker-hub-creds
    type: Opaque
---
