apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: backend-secret
spec:
  encryptedData:
    DB_PASSWORD: AgBCmptXnZrAyPAQK1J+Me65DarQQQ9nR63sv/cjDUeDip/UnQBiWEr2AuBT2K8fbkl76GkSx5bdXr94M+0iSxZHpX2g410rNh6xUW7e75GQ1T5JkDOpkBkgK54j+/+Nb2HkVmfL2qmhe+JNVhwMUH9PdU8R6vQRgDxX32aEmifEwFy/QBkfxgTHi6zIkWm4NcphgCSdjaX0zFJlI/7juFt/QRnYaro9y4Ej+SH0lG1D8QAKLnBB1+uX8TvUUfqiEo+gzFlZyVtdXNLzbjuqxbAt1LuEshfaxPK6pF6XN6cJoXm19HyezJLEb/EUCMKpngXL9yXZuhwl+VCRn7SeUuTyd+K0iuIgOBXTANz+cKF+QahTXaJi9G5on8crYeNk8PabwtJ454Iv102ZPMonu8ocRRR4LjWCbRvTy5O5g+j7sinrN7obJfEVnzjWdT2kqoR5RaSmtMyEUeGoQcD5qY/4eykh1tCzWy3u6zfMBhjailahbtozxlVnUqYcf/b0Ot7nkECk1AdpGJCf38X+C+ioYl3Z2um96iqxrbitw9DjrzYHk6UDPzeNrvfha+X3wE+nLG+Zp8YiNDO/Iu+vosvvNJrejOh9m3lK02KjM69KavixZazy+et7mEZA1z6M3zCqxhzdXg3Htv2S88Zaz43gntaGeHo/xsTXpGmR/+NOAqJPeM98TM/xpm8jm8XZGghPYpjMPqkFTkCtixuF
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: backend
      name: backend-secret
      namespace: default
    type: Opaque
---
